/** FINRESP engine scripts — load order must match original HTML. */
export const FINRESP_ENGINE_SCRIPTS = [
  'indicators/_registry.js',
  'indicators/_utils.js',
  'indicators/sma.js',
  'indicators/cma.js',
  'indicators/atr.js',
  'indicators/stoch.js',
  'indicators/tot/totstoch.js',
  'indicators/ctg/contango-series.js',
  'indicators/ctg/ctgstoch.js',
  'indicators/linreg.js',
  'indicators/bollinger.js',
  'indicators/momentum.js',
  'indicators/vwap.js',
  'indicators/cci.js',
  'indicators/macd.js',
  'indicators/rand.js',
  'logics/parser.js',
  'logics/registry.js',
  'logics/fragments.js',
  'logics/rnd.js',
  'logics/tbc.js',
  'logics/ut.js',
  'logics/uct.js',
  'logics/l5.js',
  'logics/l1.js',
  'logics/l2.js',
  'logics/l3.js',
  'logics/l4.js',
  'logics/sma_below.js',
  'logics/sma_above.js',
  'logics/sma_corridor_trend.js',
  'logics/sma_corridor_anti.js',
  'logics/fts.js',
  'logics/ftt.js',
  'logics/fts_s.js',
  'logics/ftt_s.js',
  'logics/cml.js',
  'logics/cms.js',
  'orderbook/_eval.js',
  'logics/ob_sma.js',
  'logics/ob_only.js',
  'logics/_descriptions.js',
  'connectors/registry.js',
  'connectors/broker-ops.js',
  'connectors/tbank.js',
  'connectors/alor.js',
  'trading-periods.js',
  'MultiLogic_FinrespCalculator.engine.js',
  'MultiLogic_FinrespCalculator.charts.js',
  'MultiLogic_FinrespCalculator.live.js',
] as const;

export const FINRESP_BOOTSTRAP_SCRIPTS = [
  'MultiLogic_FinrespCalculator.preboot.js',
  'MultiLogic_FinrespCalculator.boot.js',
  'MultiLogic_FinrespCalculator.fallback.js',
] as const;
